name: Build and Release
on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to release'
        required: true
        default: 'v0.18.6'

jobs:
  release:
    name: build and release
    runs-on: ubuntu-latest
    env:
      DIST_DIR: '${{ github.workspace }}/dist'
    steps:
      - uses: actions/checkout@v4
      
      - name: Set version
        id: set_version
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
            echo "VERSION=${{ github.event.inputs.tag }}" >> $GITHUB_ENV
          else
            version=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
            echo "VERSION=${version}" >> $GITHUB_ENV
          fi
          echo "version=${VERSION}" >> $GITHUB_OUTPUT

      - name: Cache Go modules
        uses: actions/cache@v3
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Setup FreeBSD environment
        uses: vmactions/freebsd-vm@v1
        with:
          usesh: true
          release: 14.1
          prepare: |
            pkg install -y node wget curl git go121 gcc bash gawk gsed jq
            ln -s /usr/local/bin/go121 /usr/local/bin/go

      - name: Build the project
        run: |
          version_num=${VERSION#v}
          git clone -b ${VERSION} https://github.com/naiba/nezha
          rm -rf nezha/pkg/geoip/geoip.db
          wget -O nezha/pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${{ secrets.IPINFO_TOKEN }}
          cd nezha/cmd/dashboard
          go build -ldflags="-s -w --extldflags '-static -fpic' -X github.com/naiba/nezha/service/singleton.Version=${version_num}"

      - name: Fix dist
        run: |
          mkdir -p "${DIST_DIR}"
          cp -rf "nezha/resource" "${DIST_DIR}"
          rm "${DIST_DIR}/resource/resource.go"
          mv -f "nezha/cmd/dashboard/dashboard" "${DIST_DIR}/nezha-dashboard"
          ls -al "${DIST_DIR}"

      - name: Prepare config.yaml
        run: |
          mkdir -p "${DIST_DIR}/data"
          cp -rf nezha/script/config.yaml "${DIST_DIR}/config.yaml"
          ls -al "${DIST_DIR}"

      - name: Compress dist files
        run: |
          cd "${DIST_DIR}"
          ls -al
          zip -r "nezha-dashboard.zip" .
          ls -al "${DIST_DIR}"

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: nezha-freebsd
          path: "${{ env.DIST_DIR }}/nezha-dashboard.zip"

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/*.zip, dist/*.tar.gz"
          generateReleaseNotes: true
          makeLatest: legacy
          omitBody: false
          omitBodyDuringUpdate: false
          omitDraftDuringUpdate: false
          omitName: false
          omitNameDuringUpdate: false
          omitPrereleaseDuringUpdate: false
          removeArtifacts: false
          replacesArtifacts: true
          skipIfReleaseExists: false
          updateOnlyUnreleased: false
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
