name: Schedule

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:  # 手动触发工作流

jobs:
  check_latest_tags:
    name: Check Latest Tags and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Get latest tag from this repository
        id: current_repo_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "")
          echo "CURRENT_REPO_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get latest tag from naiba/nezha repository
        id: nezha_repo_tag
        run: |
          NEZHA_LATEST_TAG=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
          echo "NEZHA_LATEST_TAG=$NEZHA_LATEST_TAG" >> $GITHUB_ENV

      - name: Compare tags and set build flag
        id: compare_tags
        run: |
          CURRENT_TAG=${{ env.CURRENT_REPO_TAG }}
          NEZHA_TAG=${{ env.NEZHA_LATEST_TAG }}

          if [ -z "$CURRENT_TAG" ] || [ "$CURRENT_TAG" != "$NEZHA_TAG" ]; then
            echo "Tags are different or no tag found in current repository! Triggering a new build..."
            echo "TRIGGER_BUILD=true" >> $GITHUB_OUTPUT
          else
            echo "Tags are identical. No build needed."
            echo "TRIGGER_BUILD=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger build.yml workflow
        if: steps.compare_tags.outputs.TRIGGER_BUILD == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            // owner: context.repo.owner,
            // repo: context.repo.repo,
            await github.rest.actions.createWorkflowDispatch({
              owner: 'vfhky',
              repo: 'nezha-build',
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                tag: "${{ env.NEZHA_LATEST_TAG }}"
              }
            })

  cleanup_workflow_runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 5
