name: Daily Tag Check and Build

on:
  schedule:
    - cron: '0 3 * * *'
  workflow_dispatch:

jobs:
  check_latest_tags:
    name: Check Latest Tags and Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4

      - name: Get latest tag from this repository
        id: current_repo_tag
        run: |
          LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1) || echo "")
          echo "CURRENT_REPO_TAG=$LATEST_TAG" >> $GITHUB_ENV

      - name: Get latest tag from naiba/nezha repository
        id: nezha_repo_tag
        run: |
          NEZHA_LATEST_TAG=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
          echo "NEZHA_LATEST_TAG=$NEZHA_LATEST_TAG" >> $GITHUB_ENV

      - name: Compare tags and trigger build if needed
        run: |
          CURRENT_TAG=${{ env.CURRENT_REPO_TAG }}
          NEZHA_TAG=${{ env.NEZHA_LATEST_TAG }}

          if [ -z "$CURRENT_TAG" ] || [ "$CURRENT_TAG" != "$NEZHA_TAG" ]; then
            echo "Tags are different or no tag found in current repository! Triggering a new build..."
          else
            echo "Tags are identical. No build needed."
            exit 0
          fi

      - name: Trigger build.yml workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: "build.yml",
              ref: "main",
              inputs: {
                tag: "${{ env.NEZHA_LATEST_TAG }}"
              }
            })

  cleanup_workflow_runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    needs: check_latest_tags
    steps:
      - name: Cleanup old workflow runs
        uses: AndersonFuganti/delete-workflow-runs@v2
        with:
          retention-days: 5
          delete-in-progress-runs: true
          minimum-runs: 1
