name: Schedule

on:
  schedule:
    - cron: '0 0,8,16 * * *'
  workflow_dispatch:

jobs:
  check_and_build:
    name: Check Latest Tags and Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get latest tags
        run: |
          CURRENT_REPO_TAG=$(curl -sL "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          NEZHA_LATEST_TAG=$(curl -sL "https://api.github.com/repos/naiba/nezha/releases/latest" | jq -r .tag_name)
          echo "CURRENT_REPO_TAG=${CURRENT_REPO_TAG}" >> $GITHUB_ENV
          echo "NEZHA_LATEST_TAG=${NEZHA_LATEST_TAG}" >> $GITHUB_ENV

      - name: Compare tags
        run: |
          if [ -z "${{ env.CURRENT_REPO_TAG }}" ] || [ "${{ env.CURRENT_REPO_TAG }}" != "${{ env.NEZHA_LATEST_TAG }}" ]; then
            echo "TRIGGER_BUILD=true" >> $GITHUB_ENV
          else
            echo "TRIGGER_BUILD=false" >> $GITHUB_ENV
          fi

      - name: Trigger build workflow
        if: env.TRIGGER_BUILD == 'true'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'build.yml',
              ref: 'main',
              inputs: {
                tag: "${{ env.NEZHA_LATEST_TAG }}"
              }
            })

  cleanup_runs:
    name: Cleanup Old Workflow Runs
    runs-on: ubuntu-latest
    steps:
      - name: Delete old workflow runs
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 5
          keep_minimum_runs: 5
