name: Build Nezha

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    strategy:
      fail-fast: true
      matrix:
        goos: [linux, windows]
        goarch: [amd64]
        include:
          - goos: linux
            goarch: s390x
          - goos: linux
            goarch: arm64

    runs-on: ubuntu-latest
    container:
      image: goreleaser/goreleaser-cross:v1.21
    
    env:
      GOOS: ${{ matrix.goos }}
      GOARCH: ${{ matrix.goarch }}
      GOARM: ${{ matrix.goarm }}
      DIST_DIR: ./dist

    steps:
    - name: Set up Git
      run: |
        echo "============= www ==================="
        echo "$GITHUB_WORKSPACE"
        echo "${{ github.workspace }}"
        git config --global --add safe.directory "$GITHUB_WORKSPACE"

    - name: Checkout nezha repository
      uses: actions/checkout@v4
      with:
        repository: naiba/nezha
        fetch-depth: 0

    - name: Fetch tags
      run: |
        git fetch --tags
        echo "===============0.0================"
        pwd
        echo "===============0.0================"
        ls -all .

    - name: Fetch IPInfo GeoIP Database
      env:
        IPINFO_TOKEN: ${{ secrets.IPINFO_TOKEN }}
      run: |
        rm pkg/geoip/geoip.db
        wget -qO pkg/geoip/geoip.db https://ipinfo.io/data/free/country.mmdb?token=${IPINFO_TOKEN}
        echo "===============1================"
        pwd
        ls -all .

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21.x'

    - name: Build
      uses: goreleaser/goreleaser-action@v6
      with:
        distribution: goreleaser
        version: '~> v2'
        args: build --single-target --clean --skip=validate

    - name: Install zip
      run: |
        apt-get update
        apt-get install -y zip

    - name: Prepare dist directory
      run: |
        # 查找并复制构建生成的二进制文件
        BINARY_PATH=$(find ./dist -type f -name "dashboard-${{ matrix.goos }}-${{ matrix.goarch }}" | head -n 1)

        # 创建 dashboard 目录
        mkdir -p "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/data"

        # 复制 resource 目录，排除 resource.go
        cp -rf resource "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/resource"
        rm -rf "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/resource/resource.go"

        # 复制 config.yaml 文件
        cp -rf script/config.yaml "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/data/config.yaml"
        cp -rf "$BINARY_PATH" "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/dashboard-${{ matrix.goos }}-${{ matrix.goarch }}"

        # 设置二进制文件可执行权限
        chmod +x "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}/dashboard-${{ matrix.goos }}-${{ matrix.goarch }}"

        # 列出目录内容
        ls -all "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}"

    - name: Compress artifacts into zip
      run: |
        ls -all ./
        cd "${DIST_DIR}/dist-${{ matrix.goos }}-${{ matrix.goarch }}"
        ls -all ./
        zip -qr "dashboard-${{ matrix.goos }}-${{ matrix.goarch }}.zip" .

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dashboard-${{ matrix.goos }}-${{ matrix.goarch }}.zip
        path: ./dist/dashboard-${{ matrix.goos }}-${{ matrix.goarch }}.zip

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    name: Release
    
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: ./assets

    - name: Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "assets/*.zip"
        generateReleaseNotes: true
